const SUPABASE_URL="https://zykfklcbdtotehqmjawx.supabase.co";
const SUPABASE_KEY="sb_publishable_KsHB0P3vSNl5b3IQ3tS0bg_ThX88107";
const {createClient}=supabase;
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{realtime:{params:{eventsPerSecond:30}}});
const $=id=>document.getElementById(id);
let roomId=new URLSearchParams(location.search).get("room")||"",playerName=localStorage.getItem("justus_name")||"",channel=null,players=[],soundOn=localStorage.getItem("justus_sound")!=="off",audioCtx=null;
let ready=false;
let ttt={board:Array(9).fill(""),turn:"X",winner:null};
let rps={moves:{},result:""};
let c4={board:Array(42).fill(""),turn:"R",winner:null};
let trivia={index:0,answers:{}};
let memory={cards:[],flipped:[],matched:[],turns:0};
let draw={strokes:[],drawerId:null};
let learn={stories:[]};
let wyr={index:0,votes:{}};
let voiceJoined=false,voiceMuted=false,localStream=null,peer=null,iceQueue=[];
let ytPlayer=null,ytReady=false,currentVideoId="",ytRemote=false,ytSuppress=false,ytTimer=null,ytPendingId="";
const voiceConfig={iceServers:[{urls:"stun:stun.l.google.com:19302"}]};
const triviaQuestions=[
 {q:"Which planet is known as the Red Planet?",a:["Mars","Venus","Jupiter","Mercury"],c:0},
 {q:"How many sides does a hexagon have?",a:["5","6","7","8"],c:1},
 {q:"Which ocean is the largest?",a:["Atlantic","Indian","Pacific","Arctic"],c:2},
 {q:"What is the smallest prime number?",a:["0","1","2","3"],c:2},
 {q:"Which animal is known for black-and-white stripes?",a:["Tiger","Zebra","Panda","Skunk"],c:1},
 {q:"What gas do plants mainly take in during photosynthesis?",a:["Oxygen","Nitrogen","Carbon dioxide","Helium"],c:2}
];
const questions=["What is one tiny thing that always makes you smile?","What would our perfect lazy Sunday look like?","Which memory would you replay forever?","What place should we visit together?","What song feels like us?","What is something new you want to try this year?","What is one thing you are proud of lately?"];
const wyrQuestions=[
 ["Have a surprise beach day","Have a surprise mountain day"],["Always win at board games","Always win at trivia"],["Relive your favourite day","Preview your next favourite day"],["Cook together","Order everything together"]
];
const prompts=["a sleepy cat","a rocket","a birthday cake","a tiny house","a dancing robot","a sunflower","a rainy umbrella","a bicycle","a cup of coffee","a magical castle"];
const identities=["Astronaut","Detective","Pop star","Chef","Wizard","Pirate","Superhero","Scientist","Explorer","Movie star"];
const charades=["Pretend to swim","Act like a sleepy cat","Pretend you're flying","Mime brushing your teeth","Act out a robot","Pretend you're cooking"];
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}
function playSound(kind="click"){if(!soundOn)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type="sine";o.frequency.value=kind==="pop"?680:kind==="win"?880:kind==="sparkle"?1040:420;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.12);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}catch{}}
function broadcast(event,payload){return channel?channel.send({type:"broadcast",event,payload}):Promise.resolve()}
function escapeHtml(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}
function setSound(){$("soundToggle").textContent=soundOn?"🔊 Sound on":"🔇 Sound off";localStorage.setItem("justus_sound",soundOn?"on":"off")}
function presenceUpdate(){const state=channel?.presenceState()||{};players=Object.entries(state).map(([key,vals])=>({...((vals||[])[0]||{}),key})).slice(0,10);if(players.length>10){toast("This room is full — maximum 10 players.");channel?.unsubscribe();channel=null;location.href=location.pathname;return}$('presenceText').textContent=players.length===0?"Waiting for your people…":players.length===1?"1 person here":`${players.length} people here`;$('playerCount').textContent=`${players.length} / 10`;$('presenceDot').style.background=players.length?"#50c878":"#bbb";renderPlayers();renderTTT();renderC4()}
function renderPlayers(){const box=$("playerList");box.innerHTML="";players.forEach(p=>{const d=document.createElement("div");d.className="player-chip";const name=escapeHtml(p.name||"Guest");d.innerHTML=`<span>${name}${p.host?" 👑":""}</span><span class="ready">${p.ready?"🟢 Ready":"⚪"}</span>`;box.appendChild(d)})}
function myIndex(){return players.findIndex(p=>(p.name||"")===playerName)}
function hostName(){return players[0]?.name||playerName}
function renderTTT(){const b=$("tttBoard");b.innerHTML="";ttt.board.forEach((v,i)=>{const c=document.createElement("button");c.className="ttt-cell";c.textContent=v;c.disabled=!!v||!!ttt.winner||players.length<2;c.onclick=()=>moveTTT(i);b.appendChild(c)});$("tttTurn").textContent=ttt.winner|| (players.length<2?"Waiting for 2 players…":`Turn: ${ttt.turn}`);$("tttResult").textContent=ttt.winner||""}
function winner3(b){for(const [a,c,d] of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?"draw":null}
function moveTTT(i){const idx=myIndex(),me=idx===0?"X":idx===1?"O":null;if(!me||players.length<2||ttt.board[i]||ttt.winner||ttt.turn!==me)return;const next={...ttt,board:[...ttt.board]};next.board[i]=me;const w=winner3(next.board);next.winner=w?(w==="draw"?"Draw!":`${w} wins!`):null;if(!next.winner)next.turn=me==="X"?"O":"X";ttt=next;broadcast("state",{ttt});renderTTT();playSound(next.winner?"win":"click")}
$("tttReset").onclick=()=>{if(playerName!==hostName())return toast("Only the room host can start a new game.");ttt={board:Array(9).fill(""),turn:"X",winner:null};broadcast("state",{ttt});renderTTT();playSound()};
function renderRPS(){const n=Object.keys(rps.moves).length;$("rpsStatus").textContent=n<2?"Choose your move.":"Moves are in — compare!";$("rpsResult").textContent=rps.result||""}
function rpsWinner(a,b){if(a===b)return"draw";return(a==="rock"&&b==="scissors")||(a==="scissors"&&b==="paper")||(a==="paper"&&b==="rock")?"first":"second"}
document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{rps.moves[playerName]=b.dataset.choice;rps.result="";const ids=Object.keys(rps.moves);if(ids.length>=2){const o=rpsWinner(rps.moves[ids[0]],rps.moves[ids[1]]);rps.result=o==="draw"?"It's a draw! 🤝":`${o==="first"?ids[0]:ids[1]} wins!`;}broadcast("state",{rps});renderRPS();playSound()});
$("rpsReset").onclick=()=>{if(playerName!==hostName())return toast("Only the room host can start a new round.");rps={moves:{},result:""};broadcast("state",{rps});renderRPS()};
function renderC4(){const b=$("c4Board");b.innerHTML="";c4.board.forEach((v,i)=>{const c=document.createElement("button");c.className="c4-cell";c.textContent=v==="R"?"🔴":v==="Y"?"🟡":"";c.disabled=!!v||!!c4.winner||players.length<2;c.onclick=()=>moveC4(i%7);b.appendChild(c)});$("c4Turn").textContent=c4.winner|| (players.length<2?"Waiting for 2 players…":`Turn: ${c4.turn==="R"?"🔴":"🟡"}`)}
function checkC4(b){for(let r=0;r<6;r++)for(let c=0;c<7;c++){const s=b[r*7+c];if(!s)continue;for(const[dr,dc]of[[1,0],[0,1],[1,1],[1,-1]]){let ok=true;for(let k=1;k<4;k++){const rr=r+dr*k,cc=c+dc*k;if(rr<0||rr>=6||cc<0||cc>=7||b[rr*7+cc]!==s){ok=false;break}}if(ok)return s}}return b.every(Boolean)?"draw":null}
function moveC4(col){const idx=myIndex(),me=idx===0?"R":idx===1?"Y":null;if(!me||players.length<2||c4.winner||c4.turn!==me)return;const next={...c4,board:[...c4.board]};for(let r=5;r>=0;r--){const i=r*7+col;if(!next.board[i]){next.board[i]=me;const w=checkC4(next.board);next.winner=w?(w==="draw"?"Draw!":`${w==="R"?"🔴":"🟡"} wins!`):null;if(!next.winner)next.turn=me==="R"?"Y":"R";c4=next;broadcast("state",{c4});renderC4();playSound(next.winner?"win":"click");break}}}
$("c4Reset").onclick=()=>{if(playerName!==hostName())return toast("Only the room host can start a new game.");c4={board:Array(42).fill(""),turn:"R",winner:null};broadcast("state",{c4});renderC4()};
function initMemory(){const vals=["🌙","🌙","⭐","⭐","🌷","🌷","🧸","🧸","🍓","🍓","☕","☕"];memory={cards:vals.sort(()=>Math.random()-.5),flipped:[],matched:[],turns:0};renderMemory()}
function renderMemory(){const b=$("memoryBoard");b.innerHTML="";memory.cards.forEach((v,i)=>{const c=document.createElement("button");c.className="memory-card"+(memory.flipped.includes(i)||memory.matched.includes(i)?" flipped":"");c.textContent=memory.flipped.includes(i)||memory.matched.includes(i)?v:"?";c.onclick=()=>flipMemory(i);b.appendChild(c)});$("memoryStatus").textContent=memory.matched.length===memory.cards.length?`You found them all in ${memory.turns} turns! 🎉`:`${memory.matched.length/2} / ${memory.cards.length/2} pairs found`}
function flipMemory(i){if(memory.flipped.includes(i)||memory.matched.includes(i)||memory.flipped.length>=2)return;memory.flipped.push(i);renderMemory();if(memory.flipped.length===2){memory.turns++;const[a,b]=memory.flipped;if(memory.cards[a]===memory.cards[b]){memory.matched.push(a,b);memory.flipped=[];broadcast("memory",{memory});renderMemory()}else setTimeout(()=>{memory.flipped=[];renderMemory()},650);}}
$("memoryReset").onclick=()=>{initMemory();broadcast("memory",{memory})};initMemory();
function renderTrivia(){const q=triviaQuestions[trivia.index%triviaQuestions.length];$("triviaQuestion").textContent=q.q;const w=$("triviaChoices");w.innerHTML="";q.a.forEach((a,i)=>{const b=document.createElement("button");b.className="answer-btn"+(trivia.answers[playerName]===i?" selected":"");b.textContent=a;b.onclick=()=>{trivia.answers[playerName]=i;broadcast("state",{trivia});renderTrivia();playSound()};w.appendChild(b)});const answered=Object.keys(trivia.answers).length;$("triviaStatus").textContent=answered?`${answered} player${answered===1?"":"s"} answered`:`0 / ${players.length} answered`;$('triviaScores').textContent=Object.entries(trivia.answers).map(([n,i])=>`${n}: ${i===q.c?"✓":"•"}`).join("  ")}
$("triviaNext").onclick=()=>{if(playerName!==hostName())return toast("The host controls the question.");trivia={index:(trivia.index+1)%triviaQuestions.length,answers:{}};broadcast("state",{trivia});renderTrivia()};
function resizeCanvas(c){const r=c.getBoundingClientRect(),d=window.devicePixelRatio||1;c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));const x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);x.lineWidth=4;x.lineCap="round";x.lineJoin="round";x.strokeStyle="#c98e9f"}
const drawCanvas=$("drawCanvas"),drawCtx=drawCanvas.getContext("2d");let drawing=false,last=null;
function drawLine(s){drawCtx.beginPath();drawCtx.moveTo(s.x1*drawCanvas.clientWidth,s.y1*drawCanvas.clientHeight);drawCtx.lineTo(s.x2*drawCanvas.clientWidth,s.y2*drawCanvas.clientHeight);drawCtx.stroke()}
function renderDraw(){resizeCanvas(drawCanvas);draw.strokes.forEach(drawLine);$("clearDraw").disabled=draw.drawerId!==playerName}
function attachDraw(c,getDrawer){let active=false,prev=null;c.addEventListener("pointerdown",e=>{e.preventDefault();if(getDrawer()!==playerName)return;active=true;const r=c.getBoundingClientRect();prev={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};c.setPointerCapture(e.pointerId)});c.addEventListener("pointermove",e=>{if(!active)return;e.preventDefault();const r=c.getBoundingClientRect(),p={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};const s={x1:prev.x,y1:prev.y,x2:p.x,y2:p.y};draw.strokes.push(s);drawLine(s);broadcast("draw",{stroke:s});prev=p});["pointerup","pointercancel","pointerleave"].forEach(ev=>c.addEventListener(ev,()=>{active=false;prev=null}))}
attachDraw(drawCanvas,()=>draw.drawerId);
$("drawStart").onclick=()=>{if(players.length<2)return toast("Invite someone before starting.");draw={strokes:[],drawerId:playerName};broadcast("state",{draw});renderDraw();$("drawStatus").textContent="You're drawing — start sketching!"};
$("clearDraw").onclick=()=>{if(draw.drawerId!==playerName)return;draw.strokes=[];renderDraw();broadcast("state",{draw})};
const picCanvas=$("pictionaryCanvas"),picCtx=picCanvas.getContext("2d");let picDrawing=false,picLast=null;
function resizePic(){resizeCanvas(picCanvas)}function picLine(s){picCtx.beginPath();picCtx.moveTo(s.x1*picCanvas.clientWidth,s.y1*picCanvas.clientHeight);picCtx.lineTo(s.x2*picCanvas.clientWidth,s.y2*picCanvas.clientHeight);picCtx.stroke()}
function startPic(){resizePic();picCanvas.onpointerdown=e=>{e.preventDefault();picDrawing=true;const r=picCanvas.getBoundingClientRect();picLast={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};picCanvas.setPointerCapture(e.pointerId)};picCanvas.onpointermove=e=>{if(!picDrawing)return;e.preventDefault();const r=picCanvas.getBoundingClientRect(),p={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};picLine({x1:picLast.x,y1:picLast.y,x2:p.x,y2:p.y});picLast=p};["pointerup","pointercancel"].forEach(ev=>picCanvas.addEventListener(ev,()=>{picDrawing=false;picLast=null}))}startPic();
$("pictionaryStart").onclick=()=>{$("pictionaryWord").textContent=prompts[Math.floor(Math.random()*prompts.length)];resizePic();picCtx.clearRect(0,0,picCanvas.width,picCanvas.height);toast("New drawing prompt ready 🎨")};
$("charadesBtn").onclick=()=>{$("charadesText").textContent=charades[Math.floor(Math.random()*charades.length)];playSound()};
$("whoamiBtn").onclick=()=>{$("whoamiText").textContent=identities[Math.floor(Math.random()*identities.length)];playSound()};
function renderLearn(){const stories=learn.stories||[];$("learnDate").textContent=new Date().toLocaleDateString(undefined,{day:"numeric",month:"short"});$("learnStories").innerHTML=stories.length?stories.map(s=>`<article class="learn-story"><div class="learn-story-title">${escapeHtml(s.title)}</div><div class="learn-story-meta">${escapeHtml(s.source||"Today")}</div></article>`).join(""):"<div class='learn-loading'>Loading today's stories…</div>"}
const fallbackStories=[{title:"Why our brains love tiny rewards",source:"Psychology & habits"},{title:"A simple idea from astronomy to think about today",source:"Science"},{title:"One useful productivity principle: reduce friction",source:"Productivity"},{title:"How technology is making everyday tasks smarter",source:"Technology"},{title:"The science of better sleep routines",source:"Science & wellbeing"}];
async function loadLearn(force=false){try{const rss="https://news.google.com/rss/search?q=science+technology+psychology+productivity&hl=en-IN&gl=IN&ceid=IN:en";const res=await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(rss)}`);const data=await res.json();const stories=(data.items||[]).slice(0,5).map(x=>({title:x.title,source:x.author||"Fresh news"}));learn={stories:stories.length?stories:fallbackStories};renderLearn();broadcast("learn",{state:learn});}catch{learn={stories:fallbackStories};renderLearn();if(force)toast("Using today's built-in stories while news refreshes.")}}
$("learnRefresh").onclick=()=>loadLearn(true);
function renderQuestions(){ $("dailyQuestion").textContent=questions[Math.floor(Math.random()*questions.length)] }
$("newQuestion").onclick=()=>{renderQuestions();broadcast("question",{text:$("dailyQuestion").textContent})};renderQuestions();
function renderWyr(){const q=wyrQuestions[wyr.index%wyrQuestions.length];$("wyrQuestion").textContent="Which would you choose?";$("wyrA").textContent=q[0];$("wyrB").textContent=q[1];$("wyrResult").textContent=Object.entries(wyr.votes).map(([n,v])=>`${n}: ${v===0?"A":"B"}`).join("  ")}
function voteWyr(v){wyr.votes[playerName]=v;renderWyr();broadcast("state",{wyr})}$("wyrA").onclick=()=>voteWyr(0);$("wyrB").onclick=()=>voteWyr(1);renderWyr();
function showFamily(f){$("quickPicker").classList.toggle("hidden",f!=="quick");$("partyPicker").classList.toggle("hidden",f!=="party");$("togetherPicker").classList.toggle("hidden",f!=="together");document.querySelectorAll(".game-tab").forEach(b=>b.classList.toggle("active",b.dataset.family===f));showGame(f==="quick"?"ttt":f==="party"?"trivia":"learn",true)}
function showGame(game,fromFamily=false){document.querySelectorAll(".game-box").forEach(x=>x.classList.add("hidden"));const box=$(game+"Game");if(box)box.classList.remove("hidden");document.querySelectorAll(".family-picker .tiny-btn").forEach(b=>b.classList.toggle("active-game",b.dataset.game===game));if(!fromFamily){const f=["ttt","rps","c4","memory"].includes(game)?"quick":["trivia","pictionary","charades","ludo","uno","song","whoami"].includes(game)?"party":"together";showFamily(f)}if(game==="learn")loadLearn();if(game==="draw")renderDraw()}
document.querySelectorAll(".game-tab").forEach(b=>b.onclick=()=>{showFamily(b.dataset.family);playSound()});document.querySelectorAll(".family-picker .tiny-btn").forEach(b=>b.onclick=()=>{showGame(b.dataset.game);playSound()});
function renderChatMessage(p){const wrap=$("messages"),d=document.createElement("div");d.className="message"+(p.name===playerName?" me":"");const font=p.font&&p.font!=="normal"?` font-${p.font}`:"";d.innerHTML=`<div class="message-name">${escapeHtml(p.name||"Guest")}</div><div class="message-text${font}">${p.sticker?`<span class="message-sticker">${p.sticker}</span>`:escapeHtml(p.text||"")}</div>`;wrap.appendChild(d);wrap.scrollTop=wrap.scrollHeight}
function sendChat(text,sticker=""){if(!channel)return;const payload={name:playerName,text,sticker,font:$('fontSelect').value,at:Date.now()};renderChatMessage(payload);broadcast("chat",payload);if(sticker)playSound("pop")}
$("chatForm").onsubmit=e=>{e.preventDefault();const v=$("chatInput").value.trim();if(!v)return;sendChat(v);$("chatInput").value=""};document.querySelectorAll(".tool-btn").forEach(b=>b.onclick=()=>sendChat("",b.dataset.sticker));
function runEffect(type,x=innerWidth/2,y=innerHeight*.55,remote=false){const layer=$("effectsLayer");const symbols=type==="heart"?["💗","♡","💕"]:type==="balloon"?["🎈"]:["✨","✦","⋆"];for(let i=0;i<(type==="balloon"?1:9);i++){const e=document.createElement("span");e.className=type==="heart"?"effect-heart":type==="balloon"?"effect-balloon":"effect-sparkle";e.textContent=symbols[i%symbols.length];e.style.left=(type==="balloon"?x:x+(Math.random()-.5)*20)+"px";e.style.top=(type==="balloon"?y:y+(Math.random()-.5)*20)+"px";e.style.setProperty("--dx",((Math.random()-.5)*150)+"px");e.style.setProperty("--dy",((Math.random()-.5)*150)+"px");layer.appendChild(e);setTimeout(()=>e.remove(),1500)}playSound(type==="sparkle"?"sparkle":"pop");if(!remote)broadcast("chat-effect",{type,x,y})}
document.querySelectorAll(".action-btn").forEach(b=>b.onclick=()=>runEffect(b.dataset.effect));
function setupRoom(){if(!roomId)return;$('homeView').classList.add("hidden");$('roomView').classList.remove("hidden");$('roomCode').textContent=roomId;channel=sb.channel(`just-us:${roomId}`,{config:{presence:{key:crypto.randomUUID()},broadcast:{self:false}}});channel.on("presence",{event:"sync"},presenceUpdate).on("broadcast",{event:"chat"},({payload})=>renderChatMessage(payload)).on("broadcast",{event:"chat-effect"},({payload})=>runEffect(payload.type,payload.x,payload.y,true)).on("broadcast",{event:"state"},({payload})=>{if(payload.ttt){ttt=payload.ttt;renderTTT()}if(payload.rps){rps=payload.rps;renderRPS()}if(payload.c4){c4=payload.c4;renderC4()}if(payload.trivia){trivia=payload.trivia;renderTrivia()}if(payload.draw){draw=payload.draw;renderDraw()}if(payload.wyr){wyr=payload.wyr;renderWyr()}}).on("broadcast",{event:"memory"},({payload})=>{if(payload.memory){memory=payload.memory;renderMemory()}}).on("broadcast",{event:"learn"},({payload})=>{if(payload.state){learn=payload.state;renderLearn()}}).on("broadcast",{event:"question"},({payload})=>{$("dailyQuestion").textContent=payload.text}).on("broadcast",{event:"ready"},({payload})=>{const p=players.find(x=>x.name===payload.name);if(p)p.ready=payload.ready;renderPlayers()}).on("broadcast",{event:"random-game"},({payload})=>{showGame(payload.game);toast(`Surprise game: ${payload.game}`)}).on("broadcast",{event:"voice-join"},async()=>{if(voiceJoined)makePeer(true)}).on("broadcast",{event:"voice-offer"},async({payload})=>{if(!voiceJoined)return;try{const p=makePeer(false);await p.setRemoteDescription(payload.offer);for(const c of iceQueue)await p.addIceCandidate(c).catch(()=>{});iceQueue=[];await p.setLocalDescription(await p.createAnswer());broadcast("voice-answer",{answer:p.localDescription})}catch{toast("Voice connection failed.")}}).on("broadcast",{event:"voice-answer"},async({payload})=>{if(peer)try{await peer.setRemoteDescription(payload.answer)}catch{}}).on("broadcast",{event:"voice-ice"},async({payload})=>{if(peer?.remoteDescription)await peer.addIceCandidate(payload.candidate).catch(()=>{});else iceQueue.push(payload.candidate)}).on("broadcast",{event:"voice-leave"},()=>{closePeer();$("voiceStatus").textContent="Your person left voice chat."}).on("broadcast",{event:"voice-mute"},({payload})=>{if(payload.name!==playerName)$("voiceStatus").textContent=payload.muted?"Someone muted their mic.":"Someone is unmuted."}).on("broadcast",{event:"draw"},({payload})=>{if(payload.stroke){draw.strokes.push(payload.stroke);drawLine(payload.stroke)}}).on("broadcast",{event:"youtube"},({payload})=>{if(payload.type==="load")loadYoutube(payload.id,true);else applyYT(payload)}).on("broadcast",{event:"spotify"},({payload})=>loadSpotify(payload.url));channel.subscribe(async status=>{if(status==="SUBSCRIBED"){await channel.track({name:playerName||"Guest",ready:false,host:playerName===localStorage.getItem("justus_host")});presenceUpdate();renderDraw();renderAll()}})}
function renderAll(){renderPlayers();renderTTT();renderRPS();renderC4();renderMemory();renderTrivia();renderLearn();renderQuestions();renderWyr();renderDraw();resizePic();startYTTimer()}
function parseYoutube(url){try{const u=new URL(url.trim());if(u.hostname.includes("youtu.be"))return u.pathname.slice(1).split("/")[0];if(u.hostname.includes("youtube.com"))return u.searchParams.get("v")||u.pathname.match(/\/(?:embed|shorts)\/([^/?]+)/)?.[1]||null}catch{}return null}
function onYTReady(){ytReady=true;$("youtubeStatus").innerHTML="<span>Video ready. Play it and your room will sync.</span><span>Voice stays available.</span>";if(ytPendingId){const id=ytPendingId;ytPendingId="";loadYoutube(id,ytRemote)}}
function loadYoutube(id,remote=false){if(!id)return;currentVideoId=id;ytRemote=remote;ytReady=false;if(ytPlayer?.destroy)try{ytPlayer.destroy()}catch{};$("youtubePlayer").innerHTML="";if(window.YT?.Player){ytPlayer=new YT.Player("youtubePlayer",{width:"100%",height:"100%",videoId:id,playerVars:{playsinline:1,controls:1,rel:0,modestbranding:1},events:{onReady:onYTReady,onStateChange:onYTState}})}else{ytPendingId=id;$("youtubeStatus").textContent="YouTube is loading…"}}
function onYTState(e){if(ytSuppress||ytRemote||!ytReady)return;const time=ytPlayer.getCurrentTime();if(e.data===YT.PlayerState.PLAYING)broadcast("youtube",{type:"play",id:currentVideoId,time});else if(e.data===YT.PlayerState.PAUSED)broadcast("youtube",{type:"pause",id:currentVideoId,time})}
function startYTTimer(){clearInterval(ytTimer);ytTimer=setInterval(()=>{if(!ytPlayer||!ytReady||ytRemote||ytSuppress)return;try{if(ytPlayer.getPlayerState()===YT.PlayerState.PLAYING)broadcast("youtube",{type:"sync",id:currentVideoId,time:ytPlayer.getCurrentTime()})}catch{}},1800)}
function applyYT(p){if(!ytPlayer||!ytReady||p.id!==currentVideoId)return;ytSuppress=true;try{if(typeof p.time==="number"&&Math.abs(ytPlayer.getCurrentTime()-p.time)>1.2)ytPlayer.seekTo(p.time,true);if(p.type==="play")ytPlayer.playVideo();if(p.type==="pause")ytPlayer.pauseVideo();if(p.type==="sync"&&ytPlayer.getPlayerState()===YT.PlayerState.PLAYING)ytPlayer.seekTo(p.time,true)}catch{}setTimeout(()=>ytSuppress=false,350)}
$("youtubeForm").onsubmit=e=>{e.preventDefault();const id=parseYoutube($("youtubeUrl").value);if(!id)return toast("Paste a valid YouTube video link.");loadYoutube(id,false);broadcast("youtube",{type:"load",id})};window.onYouTubeIframeAPIReady=()=>{if(ytPendingId){const id=ytPendingId;ytPendingId="";loadYoutube(id,ytRemote)}};
function parseSpotify(url){try{const u=new URL(url.trim());if(!u.hostname.includes("spotify.com"))return null;const m=u.pathname.match(/\/(track|album|playlist|episode|show)\/([A-Za-z0-9]+)/);return m?{type:m[1],id:m[2]}:null}catch{return null}}
function loadSpotify(url){const s=parseSpotify(url);if(!s)return toast("Paste a valid Spotify song, album or playlist link.");$("spotifyFrame").src=`https://open.spotify.com/embed/${s.type}/${s.id}?utm_source=generator`;$('spotifyStatus').textContent="Spotify loaded. Press play to listen."}
$("spotifyForm").onsubmit=e=>{e.preventDefault();const url=$("spotifyUrl").value.trim();if(!parseSpotify(url))return toast("Paste a valid Spotify link.");loadSpotify(url);broadcast("spotify",{url})};
async function joinVoice(){if(voiceJoined)return;try{localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});voiceJoined=true;$("joinVoiceBtn").classList.add("hidden");$("muteVoiceBtn").classList.remove("hidden");$("leaveVoiceBtn").classList.remove("hidden");$("voiceStatus").textContent="You're in the call. Your room can hear you.";broadcast("voice-join",{name:playerName})}catch{toast("Microphone permission is needed for voice chat.")}}
function makePeer(offerer){closePeer();peer=new RTCPeerConnection(voiceConfig);localStream?.getTracks().forEach(t=>peer.addTrack(t,localStream));peer.ontrack=e=>{$("remoteAudio").srcObject=e.streams[0];$('remoteAudio').play().catch(()=>{})};peer.onicecandidate=e=>{if(e.candidate)broadcast("voice-ice",{candidate:e.candidate})};if(offerer)peer.createOffer().then(o=>peer.setLocalDescription(o)).then(()=>broadcast("voice-offer",{offer:peer.localDescription}));return peer}
function closePeer(){peer?.close();peer=null;iceQueue=[]}function resetVoice(){localStream?.getTracks().forEach(t=>t.stop());localStream=null;closePeer();voiceJoined=false;voiceMuted=false;$("joinVoiceBtn").classList.remove("hidden");$("muteVoiceBtn").classList.add("hidden");$("leaveVoiceBtn").classList.add("hidden");$("muteVoiceBtn").textContent="🔇 Mute"}
$("joinVoiceBtn").onclick=joinVoice;$("leaveVoiceBtn").onclick=()=>{broadcast("voice-leave",{});resetVoice();$("voiceStatus").textContent="Join the call when you’re ready."};$("muteVoiceBtn").onclick=()=>{voiceMuted=!voiceMuted;localStream?.getAudioTracks().forEach(t=>t.enabled=!voiceMuted);$("muteVoiceBtn").textContent=voiceMuted?"🎙️ Unmute":"🔇 Mute";broadcast("voice-mute",{name:playerName,muted:voiceMuted})};
$("readyBtn").onclick=()=>{ready=!ready;$("readyBtn").textContent=ready?"↩ Not ready":"✓ Ready";broadcast("ready",{name:playerName,ready});const me=players.find(p=>p.name===playerName);if(me)me.ready=ready;renderPlayers()};
$("randomGameBtn").onclick=()=>{const pool=["ttt","rps","c4","memory","trivia","pictionary","charades","draw","wouldyou"];const game=pool[Math.floor(Math.random()*pool.length)];showGame(game);broadcast("random-game",{game});toast(`Surprise game: ${game}`)};
function openName(mode){$("nameModal").dataset.mode=mode;$("nameModal").classList.remove("hidden");$("nameInput").value=playerName;setTimeout(()=>$('nameInput').focus(),50)}
$("createRoomBtn").onclick=()=>openName("create");$("joinRoomBtn").onclick=()=>openName("join");$("closeModal").onclick=()=>$("nameModal").classList.add("hidden");$("closeJoinModal").onclick=()=>$("joinModal").classList.add("hidden");
$("nameForm").onsubmit=e=>{e.preventDefault();const n=$("nameInput").value.trim();if(!n)return;playerName=n.slice(0,24);localStorage.setItem("justus_name",playerName);$("nameModal").classList.add("hidden");if($("nameModal").dataset.mode==="create"){roomId=Math.random().toString(36).slice(2,8).toUpperCase();localStorage.setItem("justus_host",playerName);history.replaceState({},"",`?room=${roomId}`);setupRoom()}else{$("joinModal").classList.remove("hidden");setTimeout(()=>$('joinCodeInput').focus(),50)}};
$("joinForm").onsubmit=e=>{e.preventDefault();const code=$("joinCodeInput").value.trim().toUpperCase();if(code.length<4)return toast("Enter the room code.");roomId=code;history.replaceState({},"",`?room=${roomId}`);$("joinModal").classList.add("hidden");setupRoom()};
$("copyLinkBtn").onclick=async()=>{const link=`${location.origin}${location.pathname}?room=${roomId}`;try{await navigator.clipboard.writeText(link);toast("Invite link copied 💗")}catch{toast(link)}};
$("leaveRoomBtn").onclick=()=>{resetVoice();channel?.unsubscribe();channel=null;location.href=location.pathname};$("gamesNav").onclick=()=>$("gamesPanel")?.scrollIntoView({behavior:"smooth"});$("soundToggle").onclick=()=>{soundOn=!soundOn;setSound();if(soundOn)playSound()};
setSound();window.addEventListener("resize",()=>{if(!$('roomView').classList.contains('hidden')){renderDraw();resizePic()}});
if(roomId){if(playerName)setupRoom();else openName("join")}else{renderAll();showGame("ttt",true)}
